config/routes.rb
Rails.application.routes.draw do

  resources :authors
  resources :books do
    collection do
       get 'search'
       post 'picture'
      end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/picture', to: 'pictures#index'
  root 'home#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  
  validates_format_of :first_name, :last_name, :with => /\A[a-z]+\z/i
  def full_name_index(first,last)
    "#{first} #{last}"
  end

end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: :true, length: { maximum: 50 }
  validates :description, presence: :true, length: { maximum: 255, too_long: "%{count} characters is the maximum allowed" }
end

app/models/book_picture.rb
class BookPicture < ApplicationRecord
  belongs_to :book
end

app/models/picture.rb
class Picture < ApplicationRecord
  
  def self.random_photo
   # binding.pry
    pic = Unsplash::Photo.random(count: 2)
    
    @picture = []
      pic.each do |a|
      @picture << a.urls.small
    end
    @picture
  end  
  
  def self.search_photo(name)
    # binding.pry
    pic = Unsplash::Photo.search(name['search_word'], 1, 10)
    # binding.pry
    @picture = []
    pic.each do |p|
      @picture << p.urls.thumb
    end
    @picture
   
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  
  def index
    @authors = Author.all
  end
  
  def show
    @author = Author.find(params[:id])
  end
  
  def new
    @author = Author.new
  end
  
  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:success] = "New author added."
      redirect_to author_path(@author.id)
    else
      flash[:danger] = "Did you cheked the spelling?"
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
    @author = Author.find(params[:id])
    @author.delete
    redirect_to authors_path
  end
  
  private
  
  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 
  def index
    @books = Book.all
  end

  def show
    @book = Book.find_by(id: params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
      flash[:success] = "New book added to list."
    else
      flash[:danger] = "Something is not quite right."
      render new_book_path
    end
  end

  def edit
    @book = Book.find_by(id: params[:id])
  end

  def update
    @book = Book.find_by(id: params[:id])
    if @book.update_attributes(book_params)
      redirect_to book_path(@book)
      flash[:notice] = "The edit was success."
    else
      flash[:notice] = "The edit was not really successful."
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
    flash[:danger] = "OH WHY?!"
  end
  
  def search
   # binding.pry
    if search_params[:search_word].blank?
      @pic = Picture.random_photo
    else
      @pic = Picture.search_photo(search_params)
    end
  end
  
  # def picture
  #   @bookpicture = BookPicture.new(pic_parmas)
    
    
  # end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :description)
  end
  
  def search_params
    params.require(:search_params).permit(:search_word)
  end
  
  # def pic_parmas
  #   params.require(:picture).permit(:chosen_picture)
  # end
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def home
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'danger' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
  
  def full_name
    #binding.pry 
    @author[:first_name] +" "+ @author[:last_name]
  end
  
  def full_name_index(first,last)
    "#{first} #{last}"
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  

end

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/index.html.erb
<table class="table">
  
  <thead>
    <tr>
      <th><%="Id"%></th>
      <th><%="Name"%></th>
      <th><%="Delete"%></th>
    </tr>
  </thead>
  <tbody>
    
      <%@authors.each do |author|%>
     
      <tr>
       <td><%=author.id%></td>
       <td><%=author.full_name_index(author.first_name,author.last_name)%></td>
       <td><%= link_to "Delete", author_path(author.id), method: :delete%><td>
      </tr>
      <%end%>
  </tbody>
</table>

app/views/authors/new.html.erb
<%= form_for @author do |f| %>
  <%= f.label :first_name %>:
  <%= f.text_field :first_name %><br />

  <%= f.label :last_name %>:
  <%= f.text_field :last_name %><br />

  <%= f.submit %>
<% end %>

app/views/authors/show.html.erb
<%=full_name%>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
<%= form_for @book do |f| %>
  <%= f.label 'Post Title' %><br>
  <%= f.text_field :title %><br>

  <%= f.label 'Post Description' %><br>
  <%= f.text_area :description %><br>

  <%= f.submit  %>
<% end %>

app/views/books/index.html.erb
<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
  
  <tbody>
    <% @books.each do |book|%>
    <tr>
      <th scope="row"><%=link_to book.id, book_path(book.id)%></th>
      <td><%= book.title%></td>
      <td> <%= book.description%></td>
    </tr>
     <%end%>
  </tbody>
</table>

<%=link_to "New entry", new_book_path%>

<%#=link_to "Random", controller: "books", action: "random_photo"%>
<!--<a href= "<%#=random_photo%>" target="_self"> Random </a>-->
<%#= link_to "Random", picture_path %>
<%#= image_tag(@pic)%>

<!--Working-->
<!--<%#=link_to image_tag(@pic), 'https://www.google.com', target: "_blank"%>-->
<!--<%#= button_to "Picture", action: :index%>-->
<!--<%#= image_tag(@pic)%>-->
<!--<%#=link_to "Something", books_path, :method => :index%>-->

app/views/books/new.html.erb
<%= form_for @book do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :description %>:
  <%= f.text_area :description %><br />

  <%= f.submit %>
<% end %>

app/views/books/search.html.erb
<%= form_for :search_params, url: search_books_path, method: :get do |f| %>
      Search <%= f.text_field :search_word %>
    <%= f.submit 'Search' %>
  <% end %>
<br></br>


<%@pic.each do |p|%>
  <%=image_tag(p)%>
<%end%>

app/views/books/show.html.erb
<div class = "search">
  <%= form_for :search_params, url: search_books_path, method: :get do |f| %>
        Search <%= f.text_field :search_word %>
      <%= f.submit 'Search' %>
  <% end %>
</div>


<div class="card border-success mb-3" style="max-width: 18rem;">
  <div class="card-header bg-transparent border-success"><%= @book.title%></div>
  <div class="card-body text-success">
  
    <p class="card-text"><%= @book.description%></p>
  </div>
  <div class="card-footer bg-transparent border-success">
    <%=link_to "Edit", edit_book_path(@book.id)%>
    <%=link_to "Delete", book_path(@book.id), method: :delete%>
  </div>
</div>

app/views/home/home.html.erb
  <p style = "text-align: justify;">
    Books are the gates of our deepest thoughts. The deep unknown which we visit before bed, in the shower or when we want to be alone. Where everything is as it should not be, but nothing exist what it should be. No one will tell us off for the water being green and the sky being grey. Rain can be rainbow and pigs can fly. Books are the blueprints to widen our world and learn other people’s little secrets. Each and every book opens up a new universe in which we can immerse ourselves in to it. Reading is a gift and sharing our thoughts with it is as elevating as emerging from the depths of the blue water. 
  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'shared/header' %>
    
    <div class="container">
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <div class = "flash"> <%= value %> </div> 
      </div>
    <% end %>
    </div>

    
<div class="wrapper">
 <div class = "container-fluid">
  <div class = "row">
    <div class = "col-lg-4">
          
      <nav id="sidebar">
      <div class="sidebar-header">
        <h3>Menu</h3>
      </div>
        <ul class="list-unstyled components">
          <!--<p>Dummy Heading</p>-->
          <li class="active">
            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Book</a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
              <li>
                <%= link_to "List", books_path %>
              </li>
              <li>
                <%= link_to "Add", new_book_path %>
              </li>
              <li>
                <%= link_to "Show", '#' %>
              </li>
            </ul>
          </li>
          <li>
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Categories</a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
              <li>
                  <%= link_to "Science", '#' %>
              </li>
              <li>
                  <%= link_to "Classic", '#' %>
              </li>
              <li>
                  <%= link_to "Fiction", '#' %>
              </li>
            </ul>
          </li>
             <li>
              <%= link_to "About", '#' %>
          </li>
          <li>
              <%= link_to "Contact", '#' %>
          </li>
        </ul>
      </nav>
    </div>
    <div class = "col-lg-8">
      <%= yield %>
    </div>
  </div>
</div> 
    
    
  </body>
</html>

app/views/shared/_header.html.erb
 <div class="header">
      <a href="#default" class="logo">Book Collection</a>
      <div class="header-right">
        <!--<a class="active" href="#home">Home</a> -->
        <%= link_to "Home", '/', class: "btn button", form_class: "form-inline form-horizontal" %>
        <%= link_to "Login", '#', class: "btn button", form_class: "form-inline form-horizontal" %>
        <%= link_to "Sign_up", '#', class: "btn button", form_class: "form-inline form-horizontal" %>
      </div>
    </div>